blog

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -7,7 +7,7 @@ name: Deploy Astro site to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["release"]
+    branches: ["main"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -36,21 +36,22 @@ jobs:
         uses: actions/checkout@v3
       - name: Detect package manager
         id: detect-package-manager
-        run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine packager manager"
-            exit 1
-          fi
+        run: yarn 
+          # |
+          # if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          #   echo "manager=yarn" >> $GITHUB_OUTPUT
+          #   echo "command=install" >> $GITHUB_OUTPUT
+          #   echo "runner=yarn" >> $GITHUB_OUTPUT
+          #   exit 0
+          # elif [ -f "${{ github.workspace }}/package.json" ]; then
+          #   echo "manager=npm" >> $GITHUB_OUTPUT
+          #   echo "command=ci" >> $GITHUB_OUTPUT
+          #   echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          #   exit 0
+          # else
+          #   echo "Unable to determine packager manager"
+          #   exit 1
+          # fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
@@ -61,18 +62,20 @@ jobs:
         id: pages
         uses: actions/configure-pages@v3
       - name: Install dependencies
-        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+        run: yarn
+        # run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
         working-directory: ${{ env.BUILD_PATH }}
       - name: Build with Astro
-        run: |
-          ${{ steps.detect-package-manager.outputs.runner }} astro build \
-            --site "${{ steps.pages.outputs.origin }}" \
-            --base "${{ steps.pages.outputs.base_path }}"
+        run: npx 
+        # |
+        #   ${{ steps.detect-package-manager.outputs.runner }} astro build \
+        #     --site "${{ steps.pages.outputs.origin }}" \
+        #     --base "${{ steps.pages.outputs.base_path }}"
         working-directory: ${{ env.BUILD_PATH }}
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v1
         with:
-          path: ${{ env.BUILD_PATH }}/dist
+          path: ${{ env.BUILD_PATH }}/docs
 
   deploy:
     environment:
